### ISSUE TITLE
Consider adding stddef.h to fstatatcheck()

### ISSUE THREAD

**Issue by dgoerger** [ibara/mg#33]
On Alpine 3.11.x, `./configure` no-longer picks up musl's `fstatat()` implementation, and the bundled fallback code segfaults when I run the binary[1]. The compiler helpfully suggested adding `#include <stddef.h>`[2], which resolved the error for me. I confirmed that adding `stddef.h` allows `fstatatcheck` to pass on EL8[3] and Debian Buster[4], as well. Adding the header doesn't cause regression on NetBSD 8.1[5].

I haven't tested this against other operating systems like FreeBSD or macOS.

```
$ diff -u configure{.orig,}
--- configure.orig      2019-12-26 23:07:39 -0500
+++ configure   2019-12-26 23:08:45 -0500
@@ -80,6 +80,7 @@
 #define _POSIX_C_SOURCE 200809L
 #include <sys/stat.h>
 #include <fcntl.h>
+#include <stddef.h>
 int main(void){fstatat(0, NULL, NULL, 0);return 0;}
 EOF
   $cc $tflags -o conftest conftest.c > /dev/null 2>&1
```

Assuming this checks out on macOS and FreeBSD, is this something we can add to the configure script? Thanks!

[1] `gdb` output, using the fallback `fstatat` implementation in `fstatat.c`:

```
[...]
#174493 0x00007f78ca319146 in fstatat (fd=-100, path=0x7f78ca33e5c7 "", buf=0x7ffef15c6e20, flag=0) at fstatat.c:19
#174494 0x00007f78ca319146 in fstatat (fd=-100, path=0x7f78ca33e5c7 "", buf=0x7ffef15c6e20, flag=0) at fstatat.c:19
#174495 0x00007f78ca319146 in fstatat (fd=3, path=0x7f78ca33e5c7 "", buf=0x7ffef15c6e20, flag=4096) at fstatat.c:19
#174496 0x00007f78ca32a8b5 in fstat (fd=fd@entry=3, st=st@entry=0x7ffef15c6e20) at src/stat/fstat.c:10
#174497 0x00007f78ca3245b5 in realpath (filename=<optimized out>, resolved=0x7f78ca354f20 <fnb> "") at src/misc/realpath.c:31
#174498 0x00007f78ca300b09 in adjustname (fn=0x7f78ca355f20 <file> "/home/dgoerger/.mg", slashslash=1) at fileio.c:319
#174499 0x00007f78ca2fdaba in load (fname=0x7f78ca355f20 <file> "/home/dgoerger/.mg") at extend.c:644
#174500 0x00007f78ca3053c8 in main (argc=1, argv=0x7ffef15c8530) at main.c:135
```

[2] gcc's helpful error message:

```
# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.2
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
# gcc conftest.c -o conftest
conftest.c: In function 'main':
conftest.c:5:27: error: 'NULL' undeclared (first use in this function)
    5 | int main(void){fstatat(0, NULL, NULL, 0);return 0;}
      |                           ^~~~
conftest.c:5:1: note: 'NULL' is defined in header '<stddef.h>'; did you forget to '#include <stddef.h>'?
    4 | #include <fcntl.h>
  +++ |+#include <stddef.h>
    5 | int main(void){fstatat(0, NULL, NULL, 0);return 0;}
conftest.c:5:27: note: each undeclared identifier is reported only once for each function it appears in
    5 | int main(void){fstatat(0, NULL, NULL, 0);return 0;}
      |                           ^~~~
# vi conftest.c
# gcc conftest.c -o conftest
# echo $?
0
```

[3] on Red Hat Enterprise Linux 8:

```
kydoimos$ ./configure --prefix=/usr --mandir=/usr/share/man
checking for C compiler... cc
checking for -w compiler flag... yes
checking for OS... Linux
checking for fparseln... no
checking for fstatat... no
checking for futimens... yes
checking for getline... yes
checking for pledge... no
checking for reallocarray... yes
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for strtonum... no
creating Makefile... done
kydoimos$ mg configure
kydoimos$ ./configure --prefix=/usr --mandir=/usr/share/man
checking for C compiler... cc
checking for -w compiler flag... yes
checking for OS... Linux
checking for fparseln... no
checking for fstatat... yes
checking for futimens... yes
checking for getline... yes
checking for pledge... no
checking for reallocarray... yes
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for strtonum... no
creating Makefile... done
```

[4] on Debian 10 ("Buster"):

```
$ ./configure --prefix=/usr --mandir=/usr/share/man
checking for C compiler... cc
checking for -w compiler flag... yes
checking for OS... Linux
checking for fparseln... no
checking for fstatat... no
checking for futimens... yes
checking for getline... yes
checking for pledge... no
checking for reallocarray... yes
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for strtonum... no
creating Makefile... done
$ mg configure
$ ./configure --prefix=/usr --mandir=/usr/share/man
checking for C compiler... cc
checking for -w compiler flag... yes
checking for OS... Linux
checking for fparseln... no
checking for fstatat... yes
checking for futimens... yes
checking for getline... yes
checking for pledge... no
checking for reallocarray... yes
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for strtonum... no
creating Makefile... done
```

[5] on NetBSD 8.1:

```
$ ./configure --enable-static --prefix=/usr --mandir=/usr/share/man
checking for C compiler... clang
checking for -w compiler flag... yes
checking for OS... NetBSD
checking for fparseln... yes
checking for fstatat... yes
checking for futimens... yes
checking for getline... yes
checking for pledge... no
checking for reallocarray... yes
checking for strlcat... yes
checking for strlcpy... yes
checking for strndup... yes
checking for strtonum... yes
creating Makefile... done
$ mg configure
$ ./configure --enable-static --prefix=/usr --mandir=/usr/share/man
checking for C compiler... clang
checking for -w compiler flag... yes
checking for OS... NetBSD
checking for fparseln... yes
checking for fstatat... yes
checking for futimens... yes
checking for getline... yes
checking for pledge... no
checking for reallocarray... yes
checking for strlcat... yes
checking for strlcpy... yes
checking for strndup... yes
checking for strtonum... yes
creating Makefile... done
```

**Comment by ibara** [comment]
Yeah can add it. Concerned about the fallback not working but maybe it's better not to worry about fallbacks on musl systems.
